export const theme = {
  colors: {
    primary: '#003a40',
    onPrimary: '#ffffff',
    primaryContainer: '#00535b',
    onPrimaryContainer: '#86c5ce',
    secondary: '#7d5800',
    onSecondary: '#ffffff',
    secondaryContainer: '#fdca6f',
    onSecondaryContainer: '#775300',
    tertiary: '#003d2b',
    onTertiary: '#ffffff',
    tertiaryContainer: '#00563e',
    onTertiaryContainer: '#74cca8',
    background: '#f8fafa',
    onBackground: '#191c1d',
    surface: '#f8fafa',
    onSurface: '#191c1d',
    surfaceVariant: '#e1e3e3',
    onSurfaceVariant: '#3f484a',
    surfaceContainerLow: '#f2f4f4',
    surfaceContainer: '#eceeee',
    surfaceContainerHigh: '#e7e8e9',
    surfaceContainerHighest: '#e1e3e3',
    outline: '#6f797a',
    outlineVariant: '#bfc8ca',
    error: '#ba1a1a',
    onError: '#ffffff',
    errorContainer: '#ffdad6',
    onErrorContainer: '#93000a',
    primaryFixed: '#adedf7',
    primaryFixedDim: '#91d1da',
    onPrimaryFixed: '#001f23',
    onPrimaryFixedVariant: '#004f56',
    secondaryFixed: '#ffdea9',
    secondaryFixedDim: '#f0bf65',
    onSecondaryFixed: '#271900',
    onSecondaryFixedVariant: '#5e4200',
    tertiaryFixed: '#9bf4ce',
    tertiaryFixedDim: '#7fd8b3',
    onTertiaryFixed: '#002116',
    onTertiaryFixedVariant: '#00513b',
  },
  spacing: {
    base: 8,
    containerPadding: 16,
    gridMargin: 20,
    gridGutter: 16,
    stackGap: 12,
  },
  borderRadius: {
    default: 4,
    lg: 8,
    xl: 12,
    full: 9999,
  },
  typography: {
    h1: {
      fontSize: 32,
      lineHeight: 40,
      fontWeight: '600' as const,
      letterSpacing: -0.64, // -0.02em * 32
    },
    h2: {
      fontSize: 24,
      lineHeight: 32,
      fontWeight: '600' as const,
      letterSpacing: -0.24, // -0.01em * 24
    },
    h3: {
      fontSize: 20,
      lineHeight: 28,
      fontWeight: '500' as const,
      letterSpacing: 0,
    },
    bodyLarge: {
      fontSize: 16,
      lineHeight: 24,
      fontWeight: '400' as const,
      letterSpacing: 0,
    },
    bodyMedium: {
      fontSize: 14,
      lineHeight: 20,
      fontWeight: '400' as const,
      letterSpacing: 0,
    },
    button: {
      fontSize: 14,
      lineHeight: 20,
      fontWeight: '600' as const,
      letterSpacing: 0.28, // 0.02em * 14
    },
    labelMedium: {
      fontSize: 12,
      lineHeight: 16,
      fontWeight: '500' as const,
      letterSpacing: 0.6, // 0.05em * 12
    },
    titleLarge: {
      fontSize: 20,
      lineHeight: 28,
      fontWeight: '500' as const,
      letterSpacing: 0,
    },
    titleMedium: {
      fontSize: 16,
      lineHeight: 24,
      fontWeight: '500' as const,
      letterSpacing: 0.15,
    },
    labelSmall: {
      fontSize: 11,
      lineHeight: 16,
      fontWeight: '500' as const,
      letterSpacing: 0.5,
    },
  },
};
